return PlaceObj('ModDef', {
	'title', "Altered Battle Dynamics",
	'id', "D55GHCb",
	'author', "permanent666",
	'version', 923,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/BOOTSTRAP.lua",
		"CharacterEffect/HUDA_Alerted.lua",
		"CharacterEffect/ABD_Filters.lua",
		"Code/CLASS_ABD_Dynamics.lua",
		"Code/CLASS_ABD.lua",
		"Code/OR_Unit.lua",
		"Code/CLASS_ABD_Camo.lua",
		"Code/OR_UnitAwareness.lua",
		"Code/CLASS_ABD_Noise.lua",
		"Code/SETUP_Terrain.lua",
		"Code/OR_ClassDef-Zulu.lua",
		"Code/CLASS_ABD_AI.lua",
		"Code/OR_ClassDef-AI.lua",
		"Code/CLASS_ABD_Darkness.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1727731015,
	'code_hash', -193041881577734848,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Skirmisher",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "StrategicRetreat",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "TacticalRetreat",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "SeekCover",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Soldier",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "SpecialTurret",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "SpecialTurret_Sniper",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HUDA_Alerted",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ABD_Filters",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "CamoSightPenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "UnawareSightRange",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "DarknessSightMod",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "SightModMinValue",
			'ClassDisplayName', "Constant",
		}),
	},
})